export const SITE_TITLE = "CineMind AI";
export const SITE_DESCRIPTION = "Discover Movies Through Meaning.";

export const SUGGESTIONS = [
  "Mind-Bending Sci-Fi",
  "Time Travel",
  "AI Movies",
  "Psychological Thrillers",
  "Space Exploration",
  "Cyberpunk",
  "Plot Twists",
  "Philosophical Movies",
];

export const MOCK_MOVIES = [
  {
    id: "inception",
    title: "Inception",
    releaseYear: "2010",
    posterUrl: "/posters/inception.jpg",
    genres: ["Science Fiction", "Thriller", "Mystery"],
    rating: 8.8,
    recommendationScore: 92,
    overview: "A thief who steals corporate secrets through dream-sharing technology is tasked with planting an idea into a CEO's mind.",
    reasons: ["Strong genre match to the query", "High semantic relevance", "Highly rated by audiences"],
    semanticScore: 0.96,
    genreScore: 0.92,
    popularityScore: 0.88,
    ratingScore: 0.9,
    contentScore: 0.82,
  },
  {
    id: "the-matrix",
    title: "The Matrix",
    releaseYear: "1999",
    posterUrl: "/posters/the-matrix.jpg",
    genres: ["Science Fiction", "Action", "Thriller"],
    rating: 8.7,
    recommendationScore: 90,
    overview: "A hacker discovers the world is a simulation and joins a rebellion against the machines.",
    reasons: ["Strong genre match", "Relevant keyword match", "Popular with viewers"],
    semanticScore: 0.94,
    genreScore: 0.91,
    popularityScore: 0.85,
    ratingScore: 0.89,
    contentScore: 0.79,
  },
  {
    id: "interstellar",
    title: "Interstellar",
    releaseYear: "2014",
    posterUrl: "/posters/interstellar.jpg",
    genres: ["Science Fiction", "Drama", "Adventure"],
    rating: 8.6,
    recommendationScore: 88,
    overview: "Explorers travel through a wormhole in space to ensure humanity's survival.",
    reasons: ["Strong science fiction genre match", "High semantic similarity", "Highly rated"],
    semanticScore: 0.91,
    genreScore: 0.89,
    popularityScore: 0.86,
    ratingScore: 0.87,
    contentScore: 0.78,
  },
];
